sources:
  - name: Shopware6StoreApi
    handler:
      openapi:
        source: ./schema/storeApi.json
        operationHeaders:
          Content-Type: application/json
          "sw-access-key": '{env.OPENAPI_ACCESS_KEY}'